import asyncio
import random
from app.logger import logger as context_logger
from ..db import Database



class PostgresDB(Database):
    def __init__(self, name : str = "Postgres", latency : float = 0.15, fail_prob : float = 0.03):
        super().__init__(name, latency, fail_prob, True)

    async def get(self, sql: str) -> dict:
        if not self.available:
            raise Exception(f"{self.name} –Ω–µ–¥–æ—Å—Ç—É–ø–µ–Ω")
        await asyncio.sleep(random.uniform(self.latency, 2 * self.latency))
        if random.random() < self.fail_prob:
            raise Exception(f"{self.name} –æ—à–∏–±–∫–∞ –ø—Ä–∏ –∑–∞–ø—Ä–æ—Å–µ")
        return {"result": "some_data"}

    async def simulate_failure(self):
        logger = context_logger.get_logger()
        while True:
            await asyncio.sleep(random.uniform(30, 50))
            self.available = False
            logger.error(f"üí• {self.name} —É–ø–∞–ª")
            await asyncio.sleep(random.uniform(10, 20))
            self.available = True
            logger.info(f"‚úÖ {self.name} –≤–æ—Å—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω")